apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
  labels:
    app: zookeeper
spec:
  serviceName: zookeeper-headless
  replicas: 3
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      name: zookeeper
      labels:
        app: zookeeper
    spec:
      securityContext:
        fsGroup: 1001
      containers:
      - name: zookeeper
        image: docker.io/bitnami/zookeeper:3.7.0-debian-10-r215
        imagePullPolicy: "IfNotPresent"
        securityContext:
          runAsUser: 1001
        command:
         - bash
         - -ec
         - |
            # Execute entrypoint as usual after obtaining ZOO_SERVER_ID
            # check ZOO_SERVER_ID in persistent volume via myid
            # if not present, set based on POD hostname
            if [[ -f "/bitnami/zookeeper/data/myid" ]]; then
              export ZOO_SERVER_ID="$(cat /bitnami/zookeeper/data/myid)"
            else
              HOSTNAME=`hostname -s`
              if [[ $HOSTNAME =~ (.*)-([0-9]+)$ ]]; then
                ORD=${BASH_REMATCH[2]}
                export ZOO_SERVER_ID=$((ORD + 1 ))
              else
                echo "Failed to get index from hostname $HOST"
                exit 1
              fi
            fi
            exec /entrypoint.sh /run.sh
        resources:
          requests:
            cpu: 2m
            memory: 350Mi
        env:
        - name: ZOO_PORT_NUMBER
          value: "2181"
        - name: ZOO_TICK_TIME
          value: "2000"
        - name: ZOO_INIT_LIMIT
          value: "10"
        - name: ZOO_SYNC_LIMIT
          value: "5"
        - name: ZOO_MAX_CLIENT_CNXNS
          value: "60"
        - name: ZOO_4LW_COMMANDS_WHITELIST
          value: "srvr, mntr"
        - name: ZOO_SERVERS
          value: zookeeper-0.zookeeper-headless.infrastructure-dependencies.svc.cluster.local:2888:3888,zookeeper-1.zookeeper-headless.infrastructure-dependencies.svc.cluster.local:2888:3888,zookeeper-2.zookeeper-headless.infrastructure-dependencies.svc.cluster.local:2888:3888
        - name: ZOO_ENABLE_AUTH
          value: "no"
        - name: ZOO_HEAP_SIZE
          value: "1024"
        - name: ZOO_LOG_LEVEL
          value: "ERROR"
        - name: ALLOW_ANONYMOUS_LOGIN
          value: "yes"
        ports:
          - name: client
            containerPort: 2181
          - name: follower
            containerPort: 2888
          - name: election
            containerPort: 3888
        livenessProbe:
          tcpSocket:
            port: client
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 6
        readinessProbe:
          tcpSocket:
            port: client
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 6
        volumeMounts:
        - name: zkdata
          mountPath: /bitnami/zookeeper
  volumeClaimTemplates:
    - metadata:
        name: zkdata
      spec:
        accessModes:
          - "ReadWriteOnce"