apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrastructure-apps
  namespace: infrastructure-dependencies
spec:
  destination:
    name: ''
    namespace: infrastructure-dependencies
    server: 'https://kubernetes.default.svc'
  source:
    path: argo-config/argo-apps/infra-apps
    repoURL: 'https://github.com/mirsafari/demo-knative-cloudevents'
    targetRevision: HEAD
  project: infrastructure
  syncPolicy:
    automated:
      prune: true
      selfHeal: true