# Source: kafka-operator/templates/operator-rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kafka-operator
  labels:
    app.kubernetes.io/name: kafka-operator
    app.kubernetes.io/component: operator

