# Source: kafka-operator/templates/authproxy-rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kafka-operator-authproxy
  labels:
    app.kubernetes.io/name: kafka-operator
    app.kubernetes.io/component: authproxy

