apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: repo-github.com-mirsafari-demo-knative-cloudeventsbase
  namespace: argocd
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
data:
  type: Z2l0
  url: aHR0cHM6Ly9naXRodWIuY29tL21pcnNhZmFyaS9kZW1vLWtuYXRpdmUtY2xvdWRldmVudHM=
