apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zkdata-zookeeper-0
  labels:
    app: zookeeper
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zkdata-zookeeper-1
  labels:
    app: zookeeper
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zkdata-zookeeper-2
  labels:
    app: zookeeper
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi