apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-cluster
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: infrastructure-dependencies
    server: 'https://kubernetes.default.svc'
  source:
    path: kubernetes-resources/kafka-operator
    repoURL: 'https://github.com/mirsafari/demo-knative-cloudevents'
    targetRevision: HEAD
    directory:
      recurse: true
  project: infrastructure
  syncPolicy:
    automated: null