apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-operator
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: infrastructure-dependencies
    server: 'https://kubernetes.default.svc'
  source:
    path: kubernetes-resources/kafka/kafka-operator
    repoURL: 'https://github.com/mirsafari/demo-knative-cloudevents'
    targetRevision: HEAD
  project: infrastructure
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    # Needed because of metadata.annotations: Too long: must have at most 262144 bytes
    syncOptions:
    - Replace=true