apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: knative-operator
  namespace: infrastructure-dependencies
spec:
  destination:
    name: ''
    namespace: infrastructure-dependencies
    server: 'https://kubernetes.default.svc'
  source:
    path: kubernetes-resources/knative-operator
    repoURL: 'https://github.com/mirsafari/demo-knative-cloudevents'
    targetRevision: HEAD
  project: infrastructure
  syncPolicy:
    automated: null