apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infrastructure
  namespace: argocd
spec:
  description: Project holding infrastructure resrouces
  destinations:
  - namespace: infrastructure-dependencies
    server: '*'
  sourceRepos:
  - https://github.com/mirsafari/demo-knative-cloudevents
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: application
  namespace: argocd
spec:
  description: Project holding application resrouces
  destinations:
  - namespace: app
    server: '*'
  sourceRepos:
  - https://github.com/mirsafari/demo-knative-cloudevents